server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
